import type {} from 'vue-router'
export { default as WBadge } from './w-badge/w-badge.vue'
export { default as WBareButton } from './w-bare-button/w-bare-button.vue'
export { default as WBox } from './w-box/w-box.vue'
export { default as WButton } from './w-button/w-button.vue'
export { default as WCard } from './w-card/w-card.vue'
export { default as WContextMenu } from './w-context-menu/w-context-menu.vue'
export { default as WCrud } from './w-crud/w-crud.vue'
export { default as WGrid } from './w-grid/w-grid.vue'
export { default as WIcon } from './w-icon/w-icon.vue'
export { default as WInfo } from './w-info/w-info.vue'
export { default as WMain } from './w-main/w-main.vue'
export { default as WMenu } from './w-menu/w-menu.vue'
export { default as WPagination } from './w-pagination/w-pagination.vue'
export { default as WPicture } from './w-picture/w-picture.vue'
export { default as WTable } from './w-table/w-table.vue'
export { default as WTabs } from './w-tabs/w-tabs.vue'

export * from './form'
export * from './utils'
export * from './dashboard'
