export { default as WModal } from './w-modal/w-modal.vue'
export { default as WPrompt } from './w-prompt/w-prompt.vue'
export { default as WToast } from './w-toast/w-toast.vue'
export { default as WCrudTopbar } from './w-crud-topbar/w-crud-topbar.vue'
export { default as WPasswordForm } from './w-password-form/w-password-form.vue'
