#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

for ws in $(git diff --name-only --cached | grep -oE 'packages/([^/]+)'); do
  pnpm --filter="./${ws}" lint:fix
done

git rm --ignore-unmatch packages/packages
